# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Su Wang
tagline:          'Research Engineer'
description:      'Mathematics, Programming, and Chemical Engineering'
url:              https://vectorBundle.github.io

author:
  name:           'Su Wang'

paginate:         8

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/vectorBundle

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
